# Generated by Django 3.2.25 on 2026-01-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0022_problem_contest_flag_and_view_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'permissions': (('see_private_problem', 'See hidden problems'), ('edit_own_problem', 'Edit own problems'), ('edit_all_problem', 'Edit all problems'), ('edit_public_problem', 'Edit all public problems'), ('view_all_problem', 'View all problems'), ('view_testcase', 'Can view testcase'), ('manage_contest_problem', 'Manage contest problems'), ('problem_full_markup', 'Edit problems with full markup'), ('clone_problem', 'Clone problem'), ('change_public_visibility', 'Change is_public field'), ('change_manually_managed', 'Change is_manually_managed field')), 'verbose_name': 'problem', 'verbose_name_plural': 'problems'},
        ),
    ]

