# Generated by Django 3.2.25 on 2026-01-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0022_alter_contest_options'),
        ('judge', '0024_add_view_testcase_permission'),
    ]

    operations = [
    ]
