# Generated by Django 3.2.25 on 2026-01-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0025_merge_20260126_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(blank=True, help_text='Sample input for the problem.', verbose_name='sample input'),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(blank=True, help_text='Sample output for the problem.', verbose_name='sample output'),
        ),
    ]
