# Generated by Django 3.2.25 on 2026-03-01 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0026_add_sample_input_output_fields'),
        ('judge', '0027_rename_department_기타_to_중고등학생'),
    ]

    operations = [
    ]
