# Generated by Django 3.2.25 on 2026-03-01 16:54

from django.db import migrations, models
import judge.models.problem


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0028_merge_20260301_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(default='본문 내용 작성\n                                    \n## 입력 설명\n입력 제한 설명\n\n## 출력 설명\n출력 제한 설명\n', null=True, validators=[judge.models.problem.disallowed_characters_validator], verbose_name='problem body'),
        ),
    ]
